### PR TITLE
Add re-sum calculation

### PR DESCRIPTION
**Pull request by ghost**
This feature can make you spam the calculation result button instead of one time click.

### CODE REVIEW

**Comment by fadzikri** [comment]
This feature can make you spam the calculation result button instead of one time click.

**Comment by fadzikri** [comment]
Wait... what?, the codes all changed

**Comment by fadzikri** [comment]
Okay, i will rework and follow the upstream again.

**Comment by fadzikri** [comment]
Okay no conflict anymore.

**Comment by fadzikri** [comment]
Preview

https://user-images.githubusercontent.com/109416385/195973230-091f8c39-5105-4110-a0bd-9c24e4f5f998.mp4

**Comment by Emilance** [comment]
Nice feature @fadzikri , I appreciate your contribution.
Remember to star the repo to help reach more contributors who looking are  for opensource opportunities.
Thankyou

**Pull request merged**
