### PR TITLE
added bubble animation and clicking button effect.

### PR DESCRIPTION
**Pull request by khushigarg1**

### CODE REVIEW

**Comment by Emilance** [comment]
Nice feature @khushigarg1 , thanks for contributing

**Comment by khushigarg1** [comment]
Thank you, Can you add hacktoberfest-accepted label on my issue.

**Comment by khushigarg1** [comment]
Thank you, can you please give hacktoberfest-accepted label on my issue?

**Comment by khushigarg1** [comment]
Thank You!

**Pull request merged**
